### ISSUE TITLE
[BUG] foundryvtt url prefix ignored for some resources

### ISSUE THREAD

**Issue by Rohendor** [WoD5E-Developers/wod5e#118]
Hi everyone,
I have a Foundry instance running behind a domain with a URL prefix, such as http://domain.com/vtm/join. Most resources are loaded correctly, as the server appends the vtm prefix to resources path. However, some specific resources fail to load as the prefix is not inserted in the URL.

Resources affected:
- WoD_Logo.webp
- base_sidebar.webp
- Pause_Border.webp
- Pause_Overlay.webp
- base_ui_background_texture.webp
- wod5e-symbols.ttf

I think these are all the resource affected by this bug, these files exist in the filesystem, and if the prefix (vtm) is manually added to the URL, they are accessible. For example, changing the not working URL: "domain.com/systems/vtm5e/assets/fonts/wod5e-symbols.ttf" to be "domain.com/**vtm**/systems/vtm5e/assets/fonts/wod5e-symbols.ttf" allows the font file to be downloaded.

**To Reproduce**
Expose a foundry instance running the WoD5E system using a prefix

**Expected behavior**
It should load the resources correctly by taking into account the prefix

Thank you

**Comment by Veilza** [comment]
Thanks for pointing this out! I'll look into how to resolve it in a hotfix probably by the weekend.

**Comment by Veilza** [comment]
I should have a fix for you in the next release - updating all the variables to pull assets from a path relative to where the actual CSS file is rather than trying to use the base URL will probably fix things. If things don't resolve after the next hotfix, feel free to re-open this issue or reach out to me directly and we can figure out how to make things work for you.

**Comment by Rohendor** [comment]
Thank you for the quick fix, i'll test it as soon as i can
