### ISSUE TITLE
[FEATURE] No Group Limitation per Actor

### ISSUE THREAD

**Issue by BokuNC** [WoD5E-Developers/wod5e#130]
So, in the general World of Darkness, specially in Vampire the Masquerade, the "Actors" may be in more than one group. In Chicago by Night there are Coteries completely made up with members of other groups, they act together in some manner and have specific resources and domain as a group.

As is, the group sheets ony allow an actor to be part of one of these, which is kinda fine for players most of the time, but does limit the organization of a complex social system such as World of Darkness.

If a single actor could be added to two or more group sheets, it would be a great help when organizing NPCs.

**Comment by Veilza** [comment]
Unfortunately due to the way grouping works, this is not something that is planned to be implemented. While you're right, in-lore someone can belong to many coteries, that is not what the group sheets are for tracking. Group sheets are for tracking player characters, grouping player characters together, handling clan/cell/tribe functionality, and nothing more.

I would have to drastically rework how group sheets work to be able to support actors being able to have multiple groups, and that's just not something that I'm interested in implementing because the base game system mechanically does not support it.
