### ISSUE TITLE
[FEATURE] Please make it compatible with Tokenizer again

### ISSUE THREAD

**Issue by BokuNC** [WoD5E-Developers/wod5e#131]
It may be seen as a minor issue, but since the 5.0.0 update, the tokenizer is no longer compatible with this system. Neither the actor image or the title bar option to open it do anything anymore.

Don't really know what changed, but it would be awesome to have it work again.

**Comment by Veilza** [comment]
This is most likely caused by the upgrade of all the actor sheets to ApplicationV2. This is not on me to fix as ApplicationV2 is going to be Foundry standard moving forward, it's on the module to fix unless proven that it actually is a system issue. Please reach out to Tokenizer and confirm that they are going to put out an upgrade to work with actor sheets using the ApplicationV2 framework.

**Comment by BokuNC** [comment]
> This is most likely caused by the upgrade of all the actor sheets to ApplicationV2. This is not on me to fix as ApplicationV2 is going to be Foundry standard moving forward, it's on the module to fix unless proven that it actually is a system issue. Please reach out to Tokenizer and confirm that they are going to put out an upgrade to work with actor sheets using the ApplicationV2 framework.

Sorry to bother once again, i reached the developers of tokenizer and, apparently, it does work with application v2 since it does work with the new D&D5e Sheets. 

I have limited coding knowledge to check if its using such application, and would love to help the best i could.

https://github.com/MrPrimate/tokenizer/issues/182

**Comment by Veilza** [comment]
@BokuNC Specifically pinging you about this: "

**Comment by Veilza** [comment]
Next update will fix the avatar issue you were running into, I presume. Let me know if it persists past 5.0.8.

As I mentioned over in the issue on Tokenizer's repo - the header button not appearing is due to AppV2 not firing off a specific hook, which won't be re-added until V13 of core Foundry.

**Comment by BokuNC** [comment]
Thank you very musch for investigating this deeper and putting you time on this!

**Comment by Veilza** [comment]
No problem at all! Sorry for dismissing this so quickly; there's quite a few things that I just can't fix on the system's end because modules aren't updated to handle AppV2, so that was my first assumption.

Thank you for pushing the issue though! Much appreciated in making me see there actually was a bug here.

**Comment by Veilza** [comment]
Hotfix to resolve the avatar issue is now out: https://github.com/WoD5E-Developers/wod5e/releases/tag/5.0.8

**Comment by BokuNC** [comment]
Seems to be working properly now, thanks again!
