### ISSUE TITLE
[FEATURE] Actors and Items not working with PopOut Module

### ISSUE THREAD

**Issue by maxlovell73** [WoD5E-Developers/wod5e#145]
I would be great if Actors and Item windows would work with the PopOut module, as it frees up game window space to move them onto a separate screen during gaming. 

I'm using:
Foundry Version 12 Stable build 331
World of Darkness 5e 5.0.8
PopOut 2.18
libWrapper 1.13.2.0
Dice So Nice 5.1.3

The other Foundry windows feature the PopOut icon/button but not Actors and Items.

In the image below the PopOut icon can be seen in teh top right of the Module Management window and not in the Item window (Armour: Kevlar vest/flak jacket)
![image](https://github.com/user-attachments/assets/2d2dd311-5862-411b-adce-15294c2c1926)

Regards,
Max

**Comment by Veilza** [comment]
This is not on the system to fix. This is on Popout to support AppV2 sheets.

**Comment by maxlovell73** [comment]
Sorry I'll add the issue on their project.

**Comment by Veilza** [comment]
No problem at all! Sorry if I came off a bit snippy, you didn't do anything wrong.

Modules will just take some time to update to the new sheet framework that Foundry is going to be using moving forward, and the World of Darkness 5e system updated all our sheets super early. So that's why it's not working and why Popout has to fix it instead of us.

**Comment by maxlovell73** [comment]
That's OK, I'm adding it to their list.
