### ISSUE TITLE
[BUG] Edges

### ISSUE THREAD

**Issue by sillysuzie** [WoD5E-Developers/wod5e#41]
**Describe the bug**
On a Hunter sheet when you add an Edge it now says "New Arsenal" where as before it would put a perk plus show the edge category sort of like a Discipline for VtM. 

**To Reproduce**
![HunterSheet](https://github.com/user-attachments/assets/6efa34c8-9335-4f80-8912-411efd371f40)
When you add an Edge it shows the new perk only.
**Expected behavior**
It should show the new edge with what edge separating it.

**User Information**

- Browser:  Mozilla
- FoundryVTT Version: Version 12 Stable, build 350
- World of Darkness 5e system Version: 4.5.1

**Additional context**

**Comment by Veilza** [comment]
This isn't a bug - this is new expected behaviour.
- New format for creating powers is "New {Discipline/Edge/Gift Name}"
- There's no reason to show the edge category because.. all the edge categories are listed as headers. Everything under that header is the edge category and the middle section on each Perk was unnecessary.
