### ISSUE TITLE
[BUG] Discipline rouse checks are incorrect

### ISSUE THREAD

**Issue by Byroks** [WoD5E-Developers/wod5e#55]
**Describe the bug**
With Blood potency 1 I should only get a second rouse check on powers of level 1
Currently I get 1 extra die for every cost level
If cost is 1 I get 2 dice to rouse
![image](https://github.com/user-attachments/assets/941b938c-8842-4098-bd9a-372b3b8e2fff)

If the cost is 2 I get 4 dice to rouse
![image](https://github.com/user-attachments/assets/286cba43-eb30-4629-a522-6f53d63168f8)

**To Reproduce**
Set cost of a power to any number, you get double the amount of die to rouse

**User Information**

- Browser: Firefox
- FoundryVTT Version: v12
- World of Darkness 5e system Version: v5-prerelease-1

**Comment by Veilza** [comment]
This is intentional:

By rules, you re-roll the rouse check for powers if it's re-rollable, and always take the higher of the two rolls. The system simplifies this by doubling the number of hunger dice and keeping the highest half.

A vampire with Blood Potency 2 will reroll any rouse checks on level 1 discipline powers; if it has a rouse cost of 1, that means the system will roll two dice and keep the highest one. If it has a rouse cost of 2, that means it will roll four dice and keep the highest two.

A vampire with Blood Potency of 9 will reroll every single hunger dice in a rouse check for every single discipline power, whether the cost is 1 or 2.

**Comment by Byroks** [comment]
I still think this is a bug as this also happens with blood potency 0 where no reroll should be happening.

And as in the pictures it also happend with powers of level 5 and the bug description did it with BP 1

**Comment by Veilza** [comment]
I see - this actually **did** seem to be a bug. The function to check whether a rouse check was supposed to include rerolls or not was returning the data wrong, and it's been fixed now on my own development branch.

I originally thought you were saying the entire reroll function was a bug - hence, my explaining how it worked. Sorry about that!
